ALTER TABLE albums 
ADD CONSTRAINT PK_albums PRIMARY KEY CLUSTERED (id);


ALTER TABLE artists 
ADD CONSTRAINT PK_artists PRIMARY KEY CLUSTERED (id);


ALTER TABLE audio_features 
ADD CONSTRAINT PK_audoio_features PRIMARY KEY CLUSTERED (id);


ALTER TABLE genres 
ADD CONSTRAINT PK_genres PRIMARY KEY CLUSTERED (name);


ALTER TABLE tracks
ADD CONSTRAINT PK_tracks PRIMARY KEY CLUSTERED (id);


ALTER TABLE r_albums_artists
ADD CONSTRAINT FK1_r_albums_artists FOREIGN KEY (artist_id)
REFERENCES artists(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE r_albums_artists
ADD CONSTRAINT FK2_r_albums_artists FOREIGN KEY (album_id)
REFERENCES albums(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE r_albums_tracks
ADD CONSTRAINT FK1_r_albums_tracks FOREIGN KEY (album_id)
REFERENCES albums(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE r_albums_tracks
ADD CONSTRAINT FK2_r_albums_tracks FOREIGN KEY (track_id)
REFERENCES tracks(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;


ALTER TABLE r_artist_genre
ADD CONSTRAINT FK1_r_artist_genre FOREIGN KEY (genre_name)
REFERENCES genres(name)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE r_artist_genre
ADD CONSTRAINT FK2_r_artist_genre FOREIGN KEY (artist_id)
REFERENCES artists(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;


ALTER TABLE r_track_artist
ADD CONSTRAINT FK1_r_track_artist FOREIGN KEY (artist_id)
REFERENCES artists(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE r_track_artist
ADD CONSTRAINT FK2_r_track_artist FOREIGN KEY (track_id)
REFERENCES tracks(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE audio_features
ADD CONSTRAINT FK_audio_features FOREIGN KEY (id)
REFERENCES tracks(id)
ON DELETE CASCADE 
ON UPDATE CASCADE;